# https://docs.microsoft.com/en-us/dotnet/core/tools/using-ci-with-cli#travis-ci
language: csharp

solution: csharp/csharp.sln
mono: none
dotnet: 2.0.0

install:
- dotnet restore

script:
 - dotnet build
