# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AzureStorageSample' do

platform :ios, '11.0'
use_frameworks!

pod 'AZSClient'
  # Pods for AzureStorageSample

end
